source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'RealmFuse_Example' do
  pod 'RealmFuse', :path => '../'

  target 'RealmFuse_Tests' do
    inherit! :search_paths

    
  end
end
